# Generated by Django 3.2.3 on 2022-03-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
